version: 2

registries:
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "00:00"
      timezone: Australia/Brisbane
    groups:
      nuget-deps:
        patterns: [ "*" ]
    open-pull-requests-limit: 10
    registries: [ nuget ]
    target-branch: main

